version: '3'
services:
  elasticsearch:
    image: elasticsearch:5.5.0
    ports:
      - 9200
      - 9300

  logstash:
    build: ./logstash
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST:elasticsearch
    volumes:
      - /home/ubuntu/logs/nginx/download:/var/log/nginx

  kibana:
    image: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601




